// src/components/sections/spotify/Header.tsx
interface Props {
  songName: string;
  songArtist: string;
  trackId: string;
}

export default function Header({ songName, songArtist, trackId }: Props) {
  return (
    <a
      href={`https://open.spotify.com/track/${trackId}`}
      target="_blank"
      rel="noopener noreferrer"
    >
      <span className="font-newsreader underline">{songName}</span>
      <span className="text-neutral-500 text-xs"> by </span>
      <span className="font-newsreader underline">{songArtist}</span>
    </a>
  );
}

// components/spotify/Header.vue
<script setup lang="ts">
const { songName, songArtist, trackId } = defineProps<{
  songName: string;
  songArtist: string;
  trackId: string;
}>();
</script>

<template>
  <a
    :href="`https://open.spotify.com/track/${trackId}`"
    target="_blank"
    rel="noopener noreferrer"
  >
    <span class="font-newsreader underline">{{ songName }}</span>
    <span class="text-neutral-500 text-xs"> by </span>
    <span class="font-newsreader underline">{{ songArtist }}</span>
  </a>
</template>
