// src/components/Header.tsx
function HighlightedText({ children }: { children: React.ReactNode }) {
  return (
    <span className="font-newsreader text-zinc-200 text-4xl">{children}</span>
  );
}

export default function Header() {
  return (
    <header>
      <h1 className="text-3xl text-neutral-500">
        sou <HighlightedText>Victor</HighlightedText>, desenvolvedor full stack
        na <HighlightedText>Deco.cx</HighlightedText>
      </h1>
    </header>
  );
}

// components/Header.vue
<template>
  <header>
    <h1 class="text-4xl text-neutral-500">
      <span class="text-3xl">{{ $t("header.0") }}</span>
      <span class="font-newsreader text-zinc-200"> Victor</span
      ><span class="text-3xl">, {{ $t("header.1") }} </span>
      <span class="font-newsreader text-zinc-200"> Carcará.</span>
    </h1>
    <LanguageSwitch />
  </header>
</template>
